DROP VIEW IF EXISTS public.admin_members;
CREATE VIEW public.admin_members AS
SELECT
  p.id,
  p.user_id,
  p.full_name,
  p.email,
  p.avatar_url,
  p.business_name,
  p.business_type,
  p.business_address,
  p.mailing_address,
  p.region,
  p.city,
  p.gender,
  p.education_level,
  p.special_skills,
  p.bir_registration_number,
  p.nis_registration_number,
  p.vat_registration_number,
  p.has_certificate_of_registration,
  p.has_certificate_of_continuance,
  p.num_permanent_staff,
  p.num_temporary_staff,
  p.bank_name,
  p.bank_branch,
  p.membership_status,
  p.membership_type_id,
  p.membership_start_date,
  p.membership_expiry_date,
  p.is_public_directory,
  p.created_at,
  p.updated_at
FROM public.profiles p;